name: Docker

on:
  push:
    branches:
      - master
    tags:
      - '**'

env:
  DOCKER_BUILDKIT: 1
  DOCKER_BUILDKIT_INLINE_CACHE: 1
  DOCKER_IMAGE_NAME: skriptfabrik/gke-tools

jobs:
  build-push:
    name: Build and Push image
    runs-on: ubuntu-latest

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Define metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ env.DOCKER_IMAGE_NAME }}
          labels: |
            org.opencontainers.image.authors=skriptfabrik GmbH <info@skriptfabrik.com>
          tags: |
            type=raw,value=latest,enable={{is_default_branch}}
            type=semver,pattern={{version}}
            type=sha

      - name: Build and Push image
        uses: docker/build-push-action@v6
        with:
          build-args: |
            BUILDKIT_INLINE_CACHE=${{ env.DOCKER_BUILDKIT_INLINE_CACHE }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE_NAME }}:latest
          labels: ${{ steps.meta.outputs.labels }}
          platforms: |
            linux/amd64
            linux/arm64
          pull: true
          push: true
          tags: ${{ steps.meta.outputs.tags }}
